version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      rails:
        patterns:
          - "rail*"
          - "active*"
          - "action*"
          - "sprockets*"
          - "rack*"
      observability:
        patterns:
          - "opentelemetry*"
          - "sentry*"
      everything:
        patterns:
          - *

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      build:
        patterns:
          - "webpack*"
          - "*-loader"
          - "@babel/*"
          - "typescript"
          - "terser"
          - "core-js"
          - "sass"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
