stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: resume_website:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./k8s/deployment.yaml
  - applyYamlConfig:
      path: ./k8s/upload-cron.yaml
  when:
    branch:
      include:
        - master
timeout: 60
notification: {}
