version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: prereq
    command:
      - /bin/sh
      - -c
      - 'bundle install && [ -f tmp/pids/server.pid ] && rm tmp/pids/server.pid; bundle exec rails server -b 0.0.0.0'
    volumes:
      - .:/rails-app
      - 'gemsvol:/usr/local/bundle/'
      - 'binvol:/usr/local/bundle/bin'
      - 'tmpvol:/rails-app/tmp'
    stdin_open: true
    ports:
      - '127.0.0.1:32770:3000/tcp'
    environment:
      RAILS_ENV: development
  webpack:
    build:
      context: .
      dockerfile: Dockerfile
      target: npm
    environment:
      RAILS_ENV: development
    command:
      - /usr/local/bin/npm
      - run
      - dev:start
    volumes:
      - .:/rails-app
      - 'npm:/rails-app/node_modules'

volumes:
  gemsvol:
  tmpvol:
  binvol:
  npm:
