apiVersion: apps/v1
kind: Deployment
metadata:
  name: adamjacques
  namespace: personalsites
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-personalsites-adamjacques
  template:
    metadata:
      annotations:
        net.technowizardry.upgrade/skip: "true"
      labels:
        workload.user.cattle.io/workloadselector: deployment-personalsites-adamjacques
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - /rails-app/bin/bundle
            - exec
            - unicorn
            - '-o'
            - 0.0.0.0
            - '-p'
            - '8080'
            - '--no-default-middleware'
          command:
            - /usr/local/bin/ruby
          image: ajacques/resume_website
          imagePullPolicy: IfNotPresent
          name: main
          env:
            - name: OTEL_PROPAGATORS
              value: tracecontext,baggage,b3
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://collector-collector.opentelemetry.svc.cluster.local.:4318
            - name: RAILS_ENV
              value: production
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 33
        - args:
              - '-c'
              - /rails-app/nginx.conf
          command:
            - /usr/sbin/nginx
          image: ajacques/resume_website
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            limits:
              memory: 32Mi
            requests:
              memory: 16Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 33
      enableServiceLinks: false
      imagePullSecrets:
        - name: pipeline-docker-registry
