apiVersion: apps/v1
kind: Deployment
metadata:
  name: adamjacques
  namespace: personalsites
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-personalsites-adamjacques
  template:
    metadata:
      annotations:
        net.technowizardry.upgrade/skip: "true"
      labels:
        workload.user.cattle.io/workloadselector: deployment-personalsites-adamjacques
    spec:
      containers:
        - image: ajacques/resume_website
          imagePullPolicy: IfNotPresent
          name: main
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - SETGID
                - SETUID
              drop:
                - ALL
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
      imagePullSecrets:
        - name: pipeline-docker-registry
