apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-to-s3
  namespace: personalsites
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      backoffLimit: 1
      template:
        spec:
          containers:
            - args:
                - bin/sync-to-s3
              image: ajacques/resume_website
              imagePullPolicy: IfNotPresent
              name: deploy-to-s3
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 33
          restartPolicy: Never
  schedule: 0 3/12 * * *
