apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-to-s3
  namespace: personalsites
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      backoffLimit: 1
      template:
        spec:
          automountServiceAccountToken: false
          containers:
            - args:
                - bin/sync-to-s3
              image: ajacques/resume_website
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: aws-credentials
                    optional: false
              name: deploy-to-s3
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 33
          enableServiceLinks: false
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  schedule: 0 3/12 * * *
