default:
  name: John Smith
  email: jsmith@example.com
  email_subject: Resume Website Inquiry

development:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: 172.17.42.1
      port: 587
